version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  server:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ../src:/var/www/html
    environment:
      #- SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DB_HOST=${DATABASE_HOST}
      - DB_NAME=${MYSQL_DB}
      - DB_PASS=${MYSQL_ROOT_PASS}